// cmd/pureast/commands/claude_edit_test.go
package commands

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestComputeCacheKey_DeterministicAndSensitive(t *testing.T) {
	// Same inputs produce same key.
	a := computeCacheKey("task A", "context X")
	a2 := computeCacheKey("task A", "context X")
	if a != a2 {
		t.Fatalf("same inputs -> different keys: %q vs %q", a, a2)
	}

	// Task change -> different key.
	if computeCacheKey("task B", "context X") == a {
		t.Errorf("task change should change key")
	}

	// Context change -> different key.
	if computeCacheKey("task A", "context Y") == a {
		t.Errorf("context change should change key")
	}

	// Hash format: starts with cache-version prefix.
	if !strings.HasPrefix(a, cacheVersion+":") {
		t.Errorf("key should start with %q, got %q", cacheVersion+":", a)
	}
}

func TestReadCachedKey_FromHeader(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "out.go")

	wantKey := "v1:abc123"
	contents := "// Code generated by pureast.\n" +
		cacheKeyHeaderLine("// ") + wantKey + "\n" +
		"// pureast-task: something\n" +
		"\npackage foo\n"
	if err := os.WriteFile(path, []byte(contents), 0644); err != nil {
		t.Fatal(err)
	}

	got, ok := readCachedKey(path)
	if !ok {
		t.Fatal("expected cache hit, got miss")
	}
	if got != wantKey {
		t.Errorf("got %q, want %q", got, wantKey)
	}
}

func TestReadCachedKey_FileMissing(t *testing.T) {
	_, ok := readCachedKey("/no/such/file/exists.go")
	if ok {
		t.Error("missing file should be cache miss")
	}
}

func TestReadCachedKey_NoHeader(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "out.go")
	if err := os.WriteFile(path, []byte("package foo\n\nfunc X() {}\n"), 0644); err != nil {
		t.Fatal(err)
	}
	_, ok := readCachedKey(path)
	if ok {
		t.Error("file without cache-key header should be cache miss")
	}
}

func TestStripCodeFences(t *testing.T) {
	cases := []struct {
		in, want string
	}{
		{"package foo\n", "package foo"},
		{"```go\npackage foo\n```\n", "package foo"},
		{"```\npackage foo\n```", "package foo"},
		{"```go\npackage foo\n\nfunc X() {}\n```\n", "package foo\n\nfunc X() {}"},
	}
	for _, c := range cases {
		got := strings.TrimSpace(stripCodeFences(c.in))
		if got != c.want {
			t.Errorf("stripCodeFences(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestLooksLikeGo(t *testing.T) {
	cases := []struct {
		in   string
		want bool
	}{
		{"package foo\n", true},
		{"// generated\npackage foo\n", true},
		{"\n\npackage foo\n", true},
		{"## Summary\nI built a thing.\n", false},
		{"Here is the implementation:\n\npackage foo\n", false}, // prose first = bad
		{"", false},
	}
	for _, c := range cases {
		if got := looksLikeGo(c.in); got != c.want {
			t.Errorf("looksLikeGo(%q) = %v, want %v", c.in, got, c.want)
		}
	}
}

func TestIsLikelyModuleSpec(t *testing.T) {
	cases := []struct {
		in   string
		want bool
	}{
		{"github.com/foo/bar", true},
		{"github.com/foo/bar@v1.2.3", true},
		{"gopkg.in/yaml.v3", true},
		{"golang.org/x/mod", true},
		{"net/http", false},
		{"./local/pkg", false},
		{"/abs/path", false},
		{"encoding/json", false},
	}
	for _, c := range cases {
		if got := isLikelyModuleSpec(c.in); got != c.want {
			t.Errorf("isLikelyModuleSpec(%q) = %v, want %v", c.in, got, c.want)
		}
	}
}

func TestWriteWithHeader_RoundTrip(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "out.go")

	body := "package foo\n\nfunc X() int { return 1 }\n"
	key := "v1:abcdef"
	task := "test task"

	if err := writeWithHeader(path, task, key, body); err != nil {
		t.Fatal(err)
	}

	got, ok := readCachedKey(path)
	if !ok || got != key {
		t.Errorf("round trip failed: got (%q, %v), want (%q, true)", got, ok, key)
	}

	contents, _ := os.ReadFile(path)
	if !strings.Contains(string(contents), "func X()") {
		t.Errorf("body lost in round-trip; contents:\n%s", contents)
	}
	if !strings.Contains(string(contents), "pureast-task: "+task) {
		t.Errorf("task line missing; contents:\n%s", contents)
	}
}

func TestWriteWithHeader_AtomicReplace(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "out.go")

	// First write
	if err := writeWithHeader(path, "v1", "v1:first", "package a\n"); err != nil {
		t.Fatal(err)
	}
	// Replace
	if err := writeWithHeader(path, "v2", "v1:second", "package b\n"); err != nil {
		t.Fatal(err)
	}

	got, _ := readCachedKey(path)
	if got != "v1:second" {
		t.Errorf("after replace, key = %q, want v1:second", got)
	}
	contents, _ := os.ReadFile(path)
	if !strings.Contains(string(contents), "package b") {
		t.Errorf("expected new body; got:\n%s", contents)
	}
	if strings.Contains(string(contents), "package a") {
		t.Errorf("old body leaked through")
	}
}

func TestCommentPrefixFor(t *testing.T) {
	cases := []struct {
		path string
		want string
	}{
		{"foo.go", "// "},
		{"path/to/main.go", "// "},
		{"Makefile", "# "},
		{"makefile", "# "},
		{"build.mk", "# "},
		{"Dockerfile", "# "},
		{"app.dockerfile", "# "},
		{"docker-compose.yml", "# "},
		{"k8s.yaml", "# "},
		{"setup.sh", "# "},
		{"Cargo.toml", "# "},
		{"unknown.xyz", "# "}, // default
	}
	for _, c := range cases {
		if got := commentPrefixFor(c.path); got != c.want {
			t.Errorf("commentPrefixFor(%q) = %q, want %q", c.path, got, c.want)
		}
	}
}

func TestWriteWithHeader_NonGoTarget(t *testing.T) {
	dir := t.TempDir()
	makefilePath := filepath.Join(dir, "Makefile")

	body := "build:\n\tgo build ./...\n"
	if err := writeWithHeader(makefilePath, "build the project", "v1:hash123", body); err != nil {
		t.Fatal(err)
	}

	contents, _ := os.ReadFile(makefilePath)
	s := string(contents)

	// Header must use # comments (Makefile syntax), not //
	if !strings.HasPrefix(s, "# Code generated") {
		t.Errorf("Makefile header should start with '# Code generated'; got:\n%s", s)
	}
	if strings.Contains(s, "// pureast-cache-key") {
		t.Errorf("Makefile must not contain Go-style cache-key line")
	}
	if !strings.Contains(s, "# pureast-cache-key: v1:hash123") {
		t.Errorf("Makefile missing # pureast-cache-key header line; got:\n%s", s)
	}
	if !strings.Contains(s, "build:\n\tgo build") {
		t.Errorf("Makefile body missing; got:\n%s", s)
	}

	// Verify readCachedKey can read back the # prefix.
	key, ok := readCachedKey(makefilePath)
	if !ok || key != "v1:hash123" {
		t.Errorf("readCachedKey on Makefile = (%q, %v), want (v1:hash123, true)", key, ok)
	}
}

func TestLooksLikeContent_NonGo(t *testing.T) {
	cases := []struct {
		in   string
		want bool
	}{
		{"build:\n\tgo build", true},                   // Makefile content
		{"FROM golang:1.22\nCOPY . .", true},           // Dockerfile content
		{"version: '3'\nservices:\n  app: {}", true},   // compose
		{"# build the thing\nbuild:", true},            // comment-leading
		{"## Summary\nThis Makefile builds...", false}, // markdown summary
		{"Here is the Makefile:\n\nbuild:", false},     // prose preamble
		{"I've created a Dockerfile that...", false},   // prose preamble
		{"", false}, // empty
	}
	for _, c := range cases {
		if got := looksLikeContent(c.in, false); got != c.want {
			t.Errorf("looksLikeContent(%q, false) = %v, want %v", c.in, got, c.want)
		}
	}
}
