// pkg/scaffold/scaffold.go
//
// The scaffolder. Takes a validated Manifest and a project root, and
// produces one `gen.go` file per package directory. Each gen.go is
// build-ignored and contains the //go:generate directives that, when
// the user runs `go generate -tags ignore ./...`, invoke claude-edit
// to fill in the actual source files.
//
// Idempotent by design: running scaffold twice with the same manifest
// is a no-op for unchanged packages. We compare the proposed gen.go
// content against the on-disk version byte-for-byte; only differences
// trigger writes. This keeps file mtimes stable across runs, which
// matters for build caches and editors.
//
// Conservative by design: scaffold creates and updates, never deletes.
// Removing a package from the manifest leaves the existing directory
// alone. Users who want pruning can rm -rf themselves.
package scaffold

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// Result reports what scaffold did, for human-readable progress output.
type Result struct {
	Created []string // gen.go files that didn't exist before
	Updated []string // gen.go files that existed but had different content
	Skipped []string // gen.go files that already matched (idempotent no-op)
}

// Scaffold materializes the manifest as a tree of gen.go files rooted
// at projectRoot. projectRoot is typically the directory containing
// pureast.yaml, but can be set explicitly via --root.
//
// Returns a Result describing what happened. Error indicates a hard
// failure (filesystem permissions, manifest references unreachable
// paths, etc.); a nil error means every package's gen.go is now
// in the desired state.
func Scaffold(m *Manifest, projectRoot string) (*Result, error) {
	res := &Result{}

	absRoot, err := filepath.Abs(projectRoot)
	if err != nil {
		return nil, fmt.Errorf("resolve project root: %w", err)
	}
	if st, err := os.Stat(absRoot); err != nil {
		return nil, fmt.Errorf("project root %s: %w", absRoot, err)
	} else if !st.IsDir() {
		return nil, fmt.Errorf("project root %s is not a directory", absRoot)
	}

	for _, pkg := range m.SortedPackages() {
		pkgDir := filepath.Join(absRoot, filepath.FromSlash(pkg.Path))
		if err := os.MkdirAll(pkgDir, 0755); err != nil {
			return nil, fmt.Errorf("create %s: %w", pkgDir, err)
		}

		genPath := filepath.Join(pkgDir, "gen.go")
		want := renderGenFile(pkg)

		got, readErr := os.ReadFile(genPath)
		switch {
		case os.IsNotExist(readErr):
			if err := os.WriteFile(genPath, want, 0644); err != nil {
				return nil, fmt.Errorf("write %s: %w", genPath, err)
			}
			res.Created = append(res.Created, relTo(absRoot, genPath))
		case readErr != nil:
			return nil, fmt.Errorf("read %s: %w", genPath, readErr)
		case bytes.Equal(got, want):
			// Idempotent: gen.go already has the exact content we'd
			// write, so don't touch it. Preserves mtime, avoids
			// triggering build re-runs that watch for file changes.
			res.Skipped = append(res.Skipped, relTo(absRoot, genPath))
		default:
			if err := os.WriteFile(genPath, want, 0644); err != nil {
				return nil, fmt.Errorf("update %s: %w", genPath, err)
			}
			res.Updated = append(res.Updated, relTo(absRoot, genPath))
		}
	}

	return res, nil
}

// renderGenFile produces the bytes of a single gen.go for one package.
// Format:
//
//	//go:build ignore
//
//	// <doc comment if any, line by line>
//
//	//go:generate pureast claude-edit ... --output X.go
//	//go:generate pureast claude-edit ... --output Y.go
//
//	package <name>
//
// The build tag must be on its own line followed by a blank line, per
// Go's spec — otherwise the parser treats it as a regular comment.
// We're careful about that here.
func renderGenFile(pkg Package) []byte {
	var b strings.Builder

	b.WriteString("//go:build ignore\n")
	b.WriteString("\n")

	b.WriteString("// Code generated by `pureast scaffold`. DO NOT EDIT BY HAND.\n")
	b.WriteString("// Edit pureast.yaml and re-run `pureast scaffold` instead.\n")
	b.WriteString("//\n")
	b.WriteString("// This file is build-ignored. It exists solely to host //go:generate\n")
	b.WriteString("// directives that produce the package's actual source files when\n")
	b.WriteString("// `go generate -tags ignore ./...` runs.\n")

	if pkg.Doc != "" {
		b.WriteString("//\n")
		for _, line := range strings.Split(strings.TrimRight(pkg.Doc, "\n"), "\n") {
			b.WriteString("// ")
			b.WriteString(line)
			b.WriteString("\n")
		}
	}
	b.WriteString("\n")

	for _, f := range pkg.Files {
		b.WriteString(renderDirective(f))
		b.WriteString("\n")
	}
	b.WriteString("\n")

	b.WriteString("package ")
	b.WriteString(pkg.Package)
	b.WriteString("\n")

	return []byte(b.String())
}

// renderDirective produces one //go:generate line for one file. The
// directive must be a single line — Go's parser does NOT honor backslash
// continuation in //go:generate, so however long the task gets, it all
// goes on one line. (This is a real Go limitation; we comply rather
// than try to pretty-print.)
func renderDirective(f File) string {
	var args []string
	args = append(args, "pureast", "claude-edit")

	if f.Model != "" {
		args = append(args, "--model", shellQuote(f.Model))
	}

	args = append(args, "--task", shellQuote(strings.ReplaceAll(f.Task, "\n", " ")))

	for _, src := range f.Sources {
		switch {
		case src.Pkg != "":
			args = append(args, "--pkg", shellQuote(src.Pkg))
		case src.Module != "":
			args = append(args, "--module", shellQuote(src.Module))
		case src.Symbol != "":
			args = append(args, "--symbol", shellQuote(src.Symbol))
		case src.Gomod != "":
			args = append(args, "--gomod", shellQuote(src.Gomod))
		}
	}

	if f.Kind != "" && f.Kind != "all" {
		args = append(args, "--kind", f.Kind)
	}
	if f.ExportedOnly != nil && !*f.ExportedOnly {
		// claude-edit defaults to --exported=true; only emit the flag
		// to disable. Saves noise in the typical case.
		args = append(args, "--exported=false")
	}
	if f.MaxTokens > 0 {
		args = append(args, "--max-tokens", strconv.Itoa(f.MaxTokens))
	}

	args = append(args, "--output", shellQuote(f.Output))

	return "//go:generate " + strings.Join(args, " ")
}

// shellQuote wraps a value in double quotes if it contains any
// shell-significant characters, otherwise leaves it bare. We're not
// trying to be a full shell escaper — that's overkill for the
// limited character set users put in manifests — but we handle the
// common case (spaces, quotes) correctly so multi-word task strings
// work. If a user puts truly weird characters in a manifest field,
// we double-quote and escape inner double-quotes; that's enough to
// survive go's directive parser.
func shellQuote(s string) string {
	if !needsQuoting(s) {
		return s
	}
	// Double-quote and escape inner quotes/backslashes.
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"', '\\':
			b.WriteByte('\\')
		}
		b.WriteRune(r)
	}
	b.WriteByte('"')
	return b.String()
}

func needsQuoting(s string) bool {
	if s == "" {
		return true
	}
	for _, r := range s {
		switch r {
		case ' ', '\t', '"', '\'', '`', '\\', '$', '&', '|', ';', '<', '>', '(', ')', '*', '?', '[', ']', '{', '}':
			return true
		}
	}
	return false
}

// relTo returns relative if it can; absolute otherwise. For console output.
func relTo(root, path string) string {
	if rel, err := filepath.Rel(root, path); err == nil {
		return rel
	}
	return path
}
